### ISSUE TITLE
안드로이드 휠 조작 구현

### ISSUE THREAD

**Issue by jae0303** [jae0303/HelloWorldPy#15]
메카넘 휠 조작 컨트롤 구현

**Comment by songgihwan** [comment]
메카넘 휠 조작방식은 버튼을 활용하여 일정한 속도와 제한된 동작을 사용하지 않고
복잡하지만 속도와 방향면에서 linear하게 동작하기 위하여 조이스틱의 좌표값을 아두이노로 전송하여
아두이노에서 속도, 방향에서 좀 더 사용자가 원활하고 손쉬운 사용이 가능하도록 구현

출처 : http://www.akexorcist.com/2012/10/android-code-joystick-controller.html
