### ISSUE TITLE
안드로이드 옵션 설정

### ISSUE THREAD

**Issue by jae0303** [jae0303/HelloWorldPy#16]
아두이노가 확인할 사운드/모터/리미트 스위치 등에 대한 옵션 버튼 구현

**Comment by songgihwan** [comment]
AWS API Gateway와의 통신을 위해 RESTFUL의 POST 기능을 이용하여 구현하였다.

RESTFUL의 POST방식은 구글 POSTMAN을 활용하여 통신의 가능 유무를 테스트하고 이를 어플리케이션에서 적용하였다. 또한 컨트롤과 다른 DB테이블을 활용하여 컨트롤과 겹치지 않도록 하였다.

통신데이터 형식은 JSON 형식으로 Lambda에서 처리하기 쉽도록 채택하였다.
