### ISSUE TITLE
라즈베리파이 카메라 스트리밍

### ISSUE THREAD

**Issue by jae0303** [jae0303/HelloWorldPy#19]
안드로이드 어플리케이션에서 확인할 라즈베리파이 카메라 스트리밍 구현

**Comment by songgihwan** [comment]
라즈베리파이에서 mjpg 스트리밍 서버를 구축하여 안드로이드 어플리케이션의 webview를 활용하여
스트리밍 영상을 무선에서 가능하게 하였다. 
유선통신을 활용하여 스트리밍 서비스를 제공할 경우 60 프레임 이상 고화질의 영상이 끊김없이 재생가능하지만 무선통신의 경우 노이즈나 AP의 상태에 따라 영상이 끊김이 조금 생길 수 있다.

참고사항 : 1) http://www.rasplay.org/?p=7174
                  2) 2016-2 학기 집중교육 1 수업
