### ISSUE TITLE
아두이노 각 모듈 동작 구현

### ISSUE THREAD

**Issue by jae0303** [jae0303/HelloWorldPy#20]
아두이노에서 동작할 각 모듈 구현
1. 사운드 모듈
2. PIR모듈
3. 스피커 모듈
4. 레이저 모듈
5. 서브 모터 모듈

**Comment by tjdudwlsdl** [comment]
1. 사운드 모듈
 - 개별적인 값을 받기 위해 아날로그 핀에 연결 후 테스트
 - 테스트 후 유의미한 값 측정 위해 역치 설정
2. PIR 모듈
 - 동작 감지 유무 판별 위해 디지털 핀에 연결 후 테스트
 - 감지 방식이 프로젝트와 맞지 않아 리모트 스위치로 변경
2-1. 리모트 스위치
 - 각 스위치마다 방향 설정 후 디지털 핀에 연결 후 테스트 
 - 연속 값 들어오는 문제로 인해 일정 딜레이 적용
