### ISSUE TITLE
아두이노 메카넘 휠 동작 구현

### ISSUE THREAD

**Issue by jae0303** [jae0303/HelloWorldPy#21]
안드로이드에서 옵션값과 함께 들어올 x,y 좌표를 통해 실제 동작하는 아두이노 휠 코드 구현

**Comment by jae0303** [comment]
벡터 값 계산을 통해 애플리케이션에서 전송하는 x,y 좌표에 맞는 동작 구현함

**Comment by ing5uny** [comment]
아두이노Mega에 모터쉴드를 사용하여 4바퀴 각각의 회전에 맞는 알고리즘을 사용하여 원하는 방향으로 움직일 수있게 하였다. 원래 바퀴가 오른쪽으로 45도가 틀어져 있어 sin,cos을 사용하여 x,y값을 받아온 것을 각 바퀴의 속도와 앞뒤 방향으로 회전할 수있도록 만들었다. 그리고 그 메카넘 휠 차량위에 아두이노Uno, Mega, 라즈베리파이, 보조배터리를 올려  상판을 덮은 후에 인형을 사용하여 꾸몄다.
